sonar.projectKey=matthieupinceel_moncatalogue
sonar.organization=matthieupinceel
sonar.projectName=MonCatalogue

sonar.sources=server,client/js
sonar.exclusions=**/node_modules/**,**/*.sqlite,**/coverage/**

# Niveau permissif : le pipeline ne bloque pas même si le Quality Gate échoue
sonar.qualitygate.wait=false

# Pas de rapport de couverture (pas de tests pour l'instant)
sonar.coverage.exclusions=**/*

# Encodage
sonar.sourceEncoding=UTF-8
